export let defaultInterests: string[] = [
  'Food and drink',
  'Events',
  'Jobs',
  'Real estate',
  'Health and wellness',
  'Transportation',
  'Community',
  'Sports and recreation',
  'Arts and culture',
  'Education',
  'Oportunities',
  'Pets',
  'Local news',
  'Religion',
  'Politics',
  'Environment',
  'Fashion and beauty',
  'Photography',
  'Gaming',
  'Music',
  'Language',
  'Books',
  'Travel',
  'Parenting',
  'Business',
  'Networking',
  'Startups',
  'Hobbies',
  'Culture',
  'Charity',
  'Automotive',
  'Sports',
  'Social  media',
  'Entertainment',
  'History and heritage',
  'Science and technology',
  'Fashion and beauty',
  'Farming and agriculture',
  'Fitness and exercise',
  'DIY',
  'Celebrities',
  'Online marketting',
  'Finance',
  'Art and design',
  'Dating and relationships',
  'Travel and tourism',
  'Clubs',
  'Entrepreneurship',
];
