export let defaultInterests: string[] = [
  'Food and drink',
  'Events',
  'Jobs',
  'Real estate',
  'Health and wellness',
  'Transportation',
  'Community',
  'Sports and recreation',
  'Arts and culture',
  'Education',
  'Volunteer opportunities',
  'Pets',
  'Local news and information',
  'Religious organizations',
  'Political organizations',
  'Environment and sustainability',
  'Fashion and beauty',
  'Photography',
  'Gaming',
  'Music',
  'Language exchange',
  'Book clubs',
  'Travel',
  'Parenting',
  'Senior citizens',
  'Business networking',
  'Tech startups',
  'Outdoor activities',
  'Hobbies and interests',
  'Ethnic and cultural groups',
  'Charity and fundraising',
  'Home and garden',
  'Automotive',
  'Gaming and esports',
  'Social justice and activism',
  'Podcasts and media',
  'Entertainment industry',
  'History and heritage',
  'Science and technology',
  'Fashion and beauty',
  'Farming and agriculture',
  'Spiritual and religious groups',
  'Sports leagues and teams',
  'Fitness and exercise',
  'Home improvement and DIY',
  'Social media influencers',
  'Online marketplaces',
  'Personal finance and investing',
  'Art and design',
  'Dating and relationships',
  'Travel and tourism',
  'Professional networking',
  'Social clubs and organizations',
  'Entrepreneurship and startups',
];
